# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  username: deduper
  password: deduper

development:
  <<: *default
  database: deduper

test:
  <<: *default
  database: deduper_test

production:
  <<: *default
  database: deduper
